Repetitions Model
Telefonica/gymnos pull request #134
Opened 2019-11-29 10:58 UTC by AntonioFernandezViz

Gymnos components of repetition model based on utterances.

Curently, this model used Gymnos components to search the optimal supervised model that fits a local dataset loaded outside Gymnos (in next steps a dataset class will be deploy) with binary labels and sequences of phrases as features.

   - preprocessors:
        "utterances_aura_embeddings": Apply a simple preprocessing to the sequences and an embedding trained in a .pkl file from Aura logs.
        "utterances_embedding_pooling": Create a Pooling from arrays based on different types of concatenations of statistics.
   - models: Several classifiers of sklearn used in the repetition model and grids file.
   - Registration of preprocessors and models.

2019-11-29 20:17 UTC, r-salas requested changes

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_ada_boost.py
> +    def __init__(self, cv, search):
Add default parameters, for example `cv=5` and `search=None`

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_ada_boost.py
> +    def fit_generator(self, generator):
Your model doesn't support generators, you should not implement this method. By default an error is raised if you're trying to call `fit_generator` with a model that does not support generators

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_ada_boost.py
> +        probs = self.model.predict_proba(X)[:, 1]
Implement the `predict_proba` method. Don't return probabilities in this method. This method should only return metrics .

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_light_gbm.py
> +import lightgbm as lgb
This module is not installed with Gymnos. Read documentation for lazy imports (Guide/Lazy Imports)

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_light_gbm.py
> +class RepetitionLightGBM(SklearnMixin, Model):
You're overriding all the methods `SklearnMixin` implements for you. You don't need to inherit from SklearnMixin. Please read documentation for mixins (Guide/Add a model#Scikit-Learn mixin)

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_xgboost.py
> +import xgboost as xgb
Dependency should be a lazy import

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/utils/repetition_grids.py
> +import numpy as np
This file looks like constants for specific models, maybe move each constant to each model

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_knn.py
> +#
Same as `repetition_ada_boost`

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_random_forest.py
> +#
Same as `repetition_ada_boost` and `light_gbm`

2019-11-29 20:17 UTC, r-salas commented on gymnos/models/repetition_svm.py
> +#
Same as `repetition_ada_boost` and `light_gbm`

2019-11-29 20:17 UTC, r-salas commented on gymnos/preprocessors/utterances_aura_embeddings.py
> +from auracog_embeddings.embeddings import Embeddings
This looks like an Aura internal module. Add module to lazy imports. I guess this module is installable with a private PyPi server, please add documentation about how to add this private PyPi server

2019-11-29 20:17 UTC, r-salas commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +    def pooling(element, type_pooling):
All models must have the same public API. Please write this method as a private method (e.g `_apply_pooling`). It doesn't look like you're using this method so if you're not using it, please remove this method.

2019-11-29 20:17 UTC, r-salas commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +from gymnos.preprocessors.preprocessor import Preprocessor
Please use relative imports

2019-11-29 20:17 UTC, r-salas commented on gymnos/preprocessors/utterances_aura_embeddings.py
> +from gymnos.preprocessors.preprocessor import Preprocessor
Please use relative imports

2019-11-29 20:17 UTC, r-salas commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +    def __init__(self, type_pooling):
Default value?

2019-11-29 20:17 UTC, r-salas commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +        self.type_pooling = type_pooling
Assert value for `type_pooling` is valid

2019-12-03 13:38 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +        self.type_pooling = type_pooling
Done, thank you

2019-12-03 13:39 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +    def __init__(self, type_pooling):
Done, thank you

2019-12-03 13:39 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_aura_embeddings.py
> +from gymnos.preprocessors.preprocessor import Preprocessor
Done, thank you

2019-12-03 13:39 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +from gymnos.preprocessors.preprocessor import Preprocessor
Done, thank you

2019-12-03 13:39 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +    def pooling(element, type_pooling):
Done, thank you

2019-12-03 13:39 UTC, AntonioFernandezViz commented on gymnos/models/repetition_xgboost.py
> +import xgboost as xgb
Done, thank you

2019-12-03 13:39 UTC, AntonioFernandezViz commented on gymnos/models/utils/repetition_grids.py
> +import numpy as np
Done, thank you

2019-12-03 13:40 UTC, AntonioFernandezViz commented on gymnos/models/repetition_knn.py
> +#
Done, thank you

2019-12-03 13:40 UTC, AntonioFernandezViz commented on gymnos/models/repetition_random_forest.py
> +#
Done, thank you

2019-12-03 13:40 UTC, AntonioFernandezViz commented on gymnos/models/repetition_svm.py
> +#
Done, thank you

2019-12-03 13:41 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_aura_embeddings.py
> +from auracog_embeddings.embeddings import Embeddings
Done, thank you. In next pull request I will add documentation.

2019-12-03 13:42 UTC, AntonioFernandezViz commented on gymnos/models/repetition_light_gbm.py
> +class RepetitionLightGBM(SklearnMixin, Model):
I need to inherit save and restore methods from Model so I keep SklearnMixIn as super class.

2019-12-03 13:43 UTC, AntonioFernandezViz commented on gymnos/models/repetition_light_gbm.py
> +import lightgbm as lgb
Done, thank you

2019-12-03 13:43 UTC, AntonioFernandezViz commented on gymnos/models/repetition_ada_boost.py
> +        probs = self.model.predict_proba(X)[:, 1]
Done, thank you

2019-12-03 13:43 UTC, AntonioFernandezViz commented on gymnos/models/repetition_ada_boost.py
> +    def fit_generator(self, generator):
Done, thank you

2019-12-03 13:43 UTC, AntonioFernandezViz commented on gymnos/models/repetition_ada_boost.py
> +    def __init__(self, cv, search):
Done, thank you

2019-12-03 13:45 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +        self.type_pooling = type_pooling
Done, thank you!

2019-12-03 13:46 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +    def __init__(self, type_pooling):
Done, thank you!

2019-12-03 13:46 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_aura_embeddings.py
> +from gymnos.preprocessors.preprocessor import Preprocessor
Done, thank you!

2019-12-03 13:46 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +from gymnos.preprocessors.preprocessor import Preprocessor
Done, thank you!

2019-12-03 13:46 UTC, AntonioFernandezViz commented on gymnos/preprocessors/utterances_embedding_pooling.py
> +    def pooling(element, type_pooling):
Done, thank you!

2019-12-03 13:48 UTC, AntonioFernandezViz commented on gymnos/models/repetition_light_gbm.py
> +class RepetitionLightGBM(SklearnMixin, Model):
I need to inherit to use save and restore methods from SklearnMixIn class.

2019-12-03 13:48 UTC, AntonioFernandezViz commented on gymnos/models/repetition_light_gbm.py
> +import lightgbm as lgb
Done, thank you!

2019-12-03 13:48 UTC, AntonioFernandezViz commented on gymnos/models/repetition_ada_boost.py
> +        probs = self.model.predict_proba(X)[:, 1]
Done, thank you!

2019-12-03 13:49 UTC, AntonioFernandezViz commented on gymnos/models/repetition_ada_boost.py
> +    def fit_generator(self, generator):
Done, thank you!

2019-12-03 13:49 UTC, AntonioFernandezViz commented on gymnos/models/repetition_ada_boost.py
> +    def __init__(self, cv, search):
Done, thank you!

2019-12-03 13:52 UTC, AntonioFernandezViz reviewed
All changes have been done except:
- I do not erase SklearnMiin dependency because I need to inherit save and restore methods.
- Add documentation of import of auracog.embedding (in next pr I will update documentation).

2019-12-03 14:19 UTC, r-salas submitted a review, later dismissed
Great job :clap:! Documentation for lazy_imports.aura_cog and documentation for models/preprocessors is still pending. Please add docs in next PR.

2019-12-03 14:19 UTC, r-salas commented on gymnos/models/repetition_light_gbm.py
> +        self.model = lazy_imports.lightgbm.LGBMClassifier(max_depth=-1, random_state=314, silent=True, metric='None',
:ok_hand:

2019-12-04 08:20 UTC, AntonioFernandezViz commented on gymnos/models/repetition_light_gbm.py
> +        self.model = lazy_imports.lightgbm.LGBMClassifier(max_depth=-1, random_state=314, silent=True, metric='None',
Thanks!

2019-12-10 14:34 UTC, kawaits requested changes
Need further devel before getting merge. Apart form current review,
dataset and trainer integration is required.

Thanks!

2020-01-30 12:02 UTC, closed without merging