Repetition model
Telefonica/gymnos pull request #163
Opened 2020-01-31 10:44 UTC by AntonioFernandezViz

Repettion model.
Includes:
- 1 dataset class
- 6 models classes
- 2 preprocessors
-Modifications in:
   - registration of __init__.py
   - lazy Imports

2020-02-05 09:19 UTC, r-salas requested changes
Really good documentation, congrats! Note that some comments also applied to other components (e.g lazy imports for sklearn)

2020-02-05 09:19 UTC, r-salas commented on gymnos/models/repetition_svc.py
> +from sklearn.svm import SVC
Scikit-Learn is a lazy import

2020-02-05 09:19 UTC, r-salas commented on gymnos/models/repetition_random_forest.py
> +from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, ShuffleSplit
Scikit-Learn is a lazy import

2020-02-05 09:19 UTC, r-salas commented on gymnos/models/repetition_light_gbm.py
> +import scipy.stats as stats
Scipy is a lazy import

2020-02-05 09:19 UTC, r-salas commented on gymnos/preprocessors/sequences_aura_embeddings.py
> +
This component requires a module from a private PYPI server, could you add a warning in the docs explaining it?

2020-02-05 09:19 UTC, r-salas commented on docs/source/datasets/structured.rst
>  .. autoclass:: gymnos.datasets.titanic.Titanic
Add also to `docs/api_reference`. It should be automatic but right now we have to write it.

2020-02-10 16:14 UTC, AntonioFernandezViz commented on docs/source/datasets/structured.rst
>  .. autoclass:: gymnos.datasets.titanic.Titanic
Done, Thank you

2020-02-10 16:14 UTC, AntonioFernandezViz commented on gymnos/preprocessors/sequences_aura_embeddings.py
> +
Done, thank you

2020-02-10 16:15 UTC, AntonioFernandezViz commented on gymnos/models/repetition_light_gbm.py
> +import scipy.stats as stats
I remove the model because I do not use it. Thank you.

2020-02-10 16:15 UTC, AntonioFernandezViz commented on gymnos/models/repetition_random_forest.py
> +from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, ShuffleSplit
I remove the model because I do not use it. Thank you.

2020-02-10 16:16 UTC, AntonioFernandezViz commented on gymnos/models/repetition_svc.py
> +from sklearn.svm import SVC
Done, thank you.

2020-02-17 11:31 UTC, r-salas requested changes
Minor changes, overall good work :+1: 
I miss not being able to use the system E2E with an experiment. Maybe add a fake dataset, I don't know what @kawaits thinks

2020-02-17 11:31 UTC, r-salas commented on gymnos/preprocessors/sequences_aura_embeddings.py
> +            auracog_utils==0.10.0 : https://github.com/Telefonica/aura-cognitive2-utils.git
Could you write about how to add the private PYPI server? Something like this:

This preprocessor requires a module from a private PYPI server (`artifactory/pypi-aura-repo`). To add this module add the following line to `~/.pip/pip.conf`:
```
[global]
extra-index-url = http://<username>:<password>@artifactory.hi.inet/artifactory/api/pypi/pypi-aura-repo/simple
trusted-host = artifactory.hi.inet
```
where `<username>` and `<password>` are your credentials from Telefonica.

2020-02-17 11:31 UTC, r-salas commented on gymnos/utils/lazy_imports.py
> +
To avoid having a property for each submodule, could you add something like this? http://dev-aura-comp-01/docs/gymnos/en/latest/guide/lazy_imports.html#import-submodules

2020-02-17 11:31 UTC, r-salas commented on gymnos/models/repetition_knn.py
> +        cv = lazy_imports.sklearn.model_selection.ShuffleSplit(n_splits=self.cv, test_size=0.2, random_state=0)
Are you sure you don't need to import `model_selection` submodule? http://dev-aura-comp-01/docs/gymnos/en/latest/guide/lazy_imports.html#import-submodules

2020-02-17 11:31 UTC, r-salas commented on gymnos/preprocessors/sequences_aura_embeddings.py
> +            sequence = eval(sequence)
Unless absolute necessary, could you avoid using `eval`? `eval` runs any code so it can pretty dangerous

2020-02-28 08:42 UTC, AntonioFernandezViz commented on gymnos/preprocessors/sequences_aura_embeddings.py
> +            sequence = eval(sequence)
Done, thank you

2020-02-28 08:52 UTC, AntonioFernandezViz commented on gymnos/models/repetition_knn.py
> +        cv = lazy_imports.sklearn.model_selection.ShuffleSplit(n_splits=self.cv, test_size=0.2, random_state=0)
I fix it, thank you

2020-02-28 08:52 UTC, AntonioFernandezViz commented on gymnos/utils/lazy_imports.py
> +
Done, thank you

2020-02-28 08:53 UTC, AntonioFernandezViz commented on gymnos/preprocessors/sequences_aura_embeddings.py
> +            auracog_utils==0.10.0 : https://github.com/Telefonica/aura-cognitive2-utils.git
Done, thank you.

2020-03-12 13:53 UTC, closed without merging