Closes a few issues
Telefonica/gymnos pull request #83
Opened 2019-04-17 10:36 UTC by r-salas

Add more info to log, add platform details, reorganize var and preprocessors directories, merge preprocessors and transformers, fix MTE API, remove -c argument when executing from docker, option to read JSON for Kaggle credentials

2019-04-20 10:15 UTC, kawaits requested changes
Please update **documentation**:
 - session now is part of the model config:
        - architecture.rst#training
        - architecture.rst#session
        - architecture.rst#system configuration
        - examples/howto-model-handler.rst
 - fleximodel:
        - architecture.rst#models 
        - examples/howto-model-handler.rst
        - samples-> from training to dataset
           - explain implications for validation samples (no longer handled by the trainer)
        - explain new param "seed" and "shuffle" options
        - explain pros and cons of "duck-typing"
        - document new utils
        - document input_shape now part of model specific parameters
 - trackers:
        - complete current info at tracking.rst
 - platform, system and HW metrics CPU/GPU:
        - extend execution-results.rst metrics section
 - keras metrics:
        - extend execution-results.rst metrics section
 - preprocessors:
        - extend architecture.rst#datasets
 - kaggle datasets:
        - original documentation included info about 
           - how to proceed with kaggle datasets in terms of credentials
           - which datasets were supported
        - please recover this info and extend  datasets.rst with any additional recommendation (ie: when data loading fails due to a credential error )
 - nvidia-docker:
        - extend installing-gymnos.rst with info about how to get nvidia-docker, install it and how to get it up and running

2019-04-20 10:41 UTC, kawaits commented on src/experiments/mnist.json
> +        "name": "keras",
1.- Experiment should be agnostic to comercial libraries.
2.- Name should be descriptive of the model not the library.  name:" keras" seems not to provide much info
Please find alternative. We can discuss it later

2019-04-20 10:41 UTC, kawaits commented on src/experiments/tiny_imagenet.json
> +        "name": "keras",
Idem

2019-04-20 10:44 UTC, kawaits commented on src/experiments/unusual_data_usage_test.json
> +            "train": 0.8,
I do not understand this: 
I thought from now on, samples were part of the "dataset" section not "training"

2019-04-20 11:00 UTC, kawaits commented on src/lib/models/keras.py
> +    def __build_compilation_from_config(self, loss, optimizer, metrics=None):
Why this method is not part of KerasMixin. What is the criteria?

2019-04-20 11:00 UTC, kawaits commented on src/lib/models/keras.py
> +    def __build_sequential_from_config(self, sequential_config):
Why this method is not part of KerasMixin. What is the criteria?

2019-04-20 11:23 UTC, kawaits commented on src/lib/models/model.py
> +    We use duck-typing but this class is defined with 2 purposes:
What's the advantage of having duck typing?
Duck typing is **more about convenience than type safety**. Source: Cui, 2015. 
It's been said that dynamic typing in general cuts down development time. There's less boilerplate code. Code is easier to hack. With static typing, compile-time checks slow down the development process. Static typing could be used at a later point to get better performance. **Others recommend duck typing only for prototyping and never for production.**

While it's true that compile-time checks are useful to catch potential problems early, duck typing enforces following coding conventions, documentation and test-driven methodologies.

Since duck typing isn't exactly a type system, it gives programmers flexibility. In Python, for example, common things are simpler to code. While static typed languages use interfaces, such interfaces may involve excessive refactoring of client code.

2019-04-20 11:36 UTC, kawaits commented on src/lib/trainer.py
> +    def __init__(self, experiment, model, dataset, training, session, tracking):
Why we are still having session as an input for the trainer? It is used no where. 
No a model class responsability
Please modify accordingly

2019-04-20 12:05 UTC, kawaits commented on src/bin/scripts/gymnosd.py
> +        experiment=Experiment(**training_config.get("experiment", {})),  # optional field
In which scenario experiment would not be required?

2019-04-22 09:15 UTC, r-salas commented on src/bin/scripts/gymnosd.py
> +        experiment=Experiment(**training_config.get("experiment", {})),  # optional field
Right now, name and tags for experiment field are optional fields, so we could do something like this:
```json
{
   "experiment": {}
}
```
I don't think is a good idea to force to have this field if both attributes are optional.

2019-04-22 09:17 UTC, r-salas commented on src/experiments/unusual_data_usage_test.json
> +            "train": 0.8,
That's how it is.

2019-04-22 09:27 UTC, r-salas commented on src/lib/models/keras.py
> +    def __build_compilation_from_config(self, loss, optimizer, metrics=None):
You're right. I'm getting on it.

2019-04-22 09:27 UTC, r-salas commented on src/lib/models/keras.py
> +    def __build_sequential_from_config(self, sequential_config):
You're right. I'm getting on it.

2019-04-22 10:08 UTC, r-salas commented on src/lib/models/keras.py
> +    def __build_compilation_from_config(self, loss, optimizer, metrics=None):
I'm reviewing the files and they are correctly defined. The keras mixin expects a `self.model` variable with a compiled keras model, it does not have a constructor. The keras model is the responsible for defining the model from the sequential and compilation parameters.

2019-04-22 10:09 UTC, r-salas commented on src/lib/models/keras.py
> +    def __build_sequential_from_config(self, sequential_config):
Idem

2019-04-29 06:50 UTC, kawaits commented on Pipfile.lock
>          "boto3": {
¿AWS?

2019-04-29 06:51 UTC, kawaits commented on Pipfile.lock
>          "botocore": {
¿AWS?

2019-04-29 07:12 UTC, kawaits commented on docs/source/trackers.rst
> +###############################
Please combine with  https://github.com/Telefonica/gymnos/blob/devel/docs/source/tracking.rst

2019-04-29 07:59 UTC, r-salas commented on Pipfile.lock
>          "boto3": {
MLFlow dependency.

2019-04-29 08:01 UTC, r-salas commented on Pipfile.lock
>          "botocore": {
MLFlow dependency

2019-05-06 09:26 UTC, r-salas commented
This branch can be merged. 
New features:
- Regression test (#46)
- Updated and extended documentation (#16, #55, #66)
- HW details for metrics and logging (#64)
- Tensorflow session builder (#64)
- Preprocessors short logging (#67)
- Metrics short logging (#68)
- Remove Docker -c option (#69)
- Model flexibility (#73)
- Dataset flexibility
- Fix M+ API MTE (#74)
- Better handling Kaggle credentials (#75)
- Unify preprocessors and transformers (#81)
- Closes #82 (outdated)
- Updated TensorFlow version (#88)
- Add data usage model to regression test (#54)

2019-05-06 14:08 UTC, merged