Predictor
Telefonica/gymnos pull request #98
Opened 2019-05-27 07:25 UTC by AntonioFernandezViz

Module predictor added:
- Implemented for programatic mode.
- Launching with p mode using dataset path with file that will be scored and execution path with trained model for apply.

2019-05-27 09:41 UTC, r-salas requested changes

2019-05-27 09:41 UTC, r-salas commented on src/bin/scripts/gymnosd.py
> +    group.add_argument("-p", "--scoring_table_path_and_configuration_path",
The -p argument should indicate the execution path, i.e, from execution path:
1. Parse configuration file to get `core.model` and `core.dataset`
2. Restore model and preprocessors
3. Instantiate predictor from `core.model` and `core.dataset` -> `predictor = Predictor(model, dataset)`
4. Predict values from predictor -> `predictions = predictor.predict(values)`

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +        platform_details = {
If you're going to use the same info from trainer, maybe refactor into a function?

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +        with elapsed_time() as elapsed:
I don't understand why we need the dataset. The only thing we need from `core.dataset` are preprocessors

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +                scoring_table, y = dataset.dataset.load_data(**load_data_arguments)
What do you mean by scoring table?

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +            dataset.preprocessor_pipeline.restore(
We restore weights/parameters before predict function,  i,e weights should be already restored

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +            model.model.restore(trainings_dataset_execution_artifacts_path)
Same, model should be already restored

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +        with elapsed_time() as elapsed, chdir(trainings_dataset_execution_artifacts_path):
Why are you using `chdir`? `chdir` is to temporary change current working directory. The trainer uses this function as a hack to allow models store artifacts during training e.g outputs from callbacks

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +    def __init__(self, trained_model_config_path="",
Add `core.dataset` and `core.model` parameters to init. We don't need the format because the user has send us the execution path

2019-05-27 09:41 UTC, r-salas commented on src/lib/predictor.py
> +    def predict(self, model, dataset):
I think the only parameter for `predict` has to be `X`. This value will be feed to preprocessors and model.

2019-05-27 09:41 UTC, r-salas commented on src/bin/scripts/gymnosd.py
> +    elif args.scoring_table_path_and_configuration_path:
Maybe we need to give two parameters to predict, i.e execution_dir and to_predict. Maybe give some intelligence to to gymnosd and check the file type, e.g [is a csv? -> read with pandas dataframe, is an image? -> read with `imread_rgb`]. I'm not sure about this because maybe we are overcomplicating  gymnosd. At the moment I would try with the single parameter and try manual data.

2019-05-27 10:23 UTC, r-salas commented
If several people on the cognitive team use PyCharm, maybe we could add `.idea` to `.gitignore`

2019-05-28 10:54 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +        platform_details = {
fixed, thanks.

2019-05-28 10:54 UTC, AntonioFernandezViz commented on src/bin/scripts/gymnosd.py
> +    group.add_argument("-p", "--scoring_table_path_and_configuration_path",
fixed, thanks.

2019-05-28 10:55 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +                scoring_table, y = dataset.dataset.load_data(**load_data_arguments)
I refered to dataset that will be scored. Fixed, thanks.

2019-05-28 10:55 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +            dataset.preprocessor_pipeline.restore(
Fixed, thanks.

2019-05-28 10:55 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +            model.model.restore(trainings_dataset_execution_artifacts_path)
Fixed, thanks.

2019-05-28 10:56 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +        with elapsed_time() as elapsed, chdir(trainings_dataset_execution_artifacts_path):
Erased, thanks

2019-05-28 10:56 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +    def __init__(self, trained_model_config_path="",
fixed, thanks.

2019-05-28 10:57 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +    def predict(self, model, dataset):
Fixed, thank you.

2019-05-28 10:58 UTC, AntonioFernandezViz commented on src/bin/scripts/gymnosd.py
> +    elif args.scoring_table_path_and_configuration_path:
I remove the every option, now it is a function that is called in programatic mode. Fixed, Thank you.

2019-05-28 10:59 UTC, AntonioFernandezViz commented
Included in git ignored, thank you.

2019-05-28 12:49 UTC, r-salas requested changes
Some minor modifications are required but good job!

2019-05-28 12:49 UTC, r-salas commented on src/lib/predictor.py
> +        execution_steps_elapsed = {}
If you're not going to return this variable, don't save elapsed times

2019-05-28 12:49 UTC, r-salas commented on src/lib/predictor.py
> +    def predict(self, values):
To follow model nomenclature, maybe rename to `X`

2019-05-28 12:49 UTC, r-salas commented on src/bin/scripts/gymnosd.py
> +def run_prediction(execution_dir, values, loggging_config_path_prediction):
The path to logging config is a constant (`LOGGING_CONFIG_PATH`), you don't need it as a parameter. You can do something like this:
```py
def configure_logging():
    logging_config = read_from_json(LOGGING_CONFIG_PATH)
    logging.config.dictConfig(logging_config)
```

And call the function  before `if args.regression_test:`

2019-05-28 15:11 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +    def predict(self, values):
fixed, thanks

2019-05-28 15:12 UTC, AntonioFernandezViz commented on src/lib/predictor.py
> +        execution_steps_elapsed = {}
fixed, thank you

2019-05-28 15:12 UTC, AntonioFernandezViz commented on src/bin/scripts/gymnosd.py
> +def run_prediction(execution_dir, values, loggging_config_path_prediction):
Done, thanks.

2019-05-28 15:15 UTC, r-salas approved these changes
Everything's fine, thanks!

2019-05-29 12:52 UTC, merged